version: '3.8'

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3010:3009"

  postgres:
    restart: always
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Kaito1@3
      POSTGRES_DB: test
    volumes:
      - ./docker/db/test.sql:/docker-entrypoint-initdb.d/test.sql

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
    restart: unless-stopped
